### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by mike6626** [halturin/applepay#11]
Currently getting this error and I am at a loss at.

shared_secred = self._private_key.exchange(ec.ECDH(), public_key)
AttributeError: '_RSAPrivateKey' object has no attribute 'exchange' Line 71 payment.py

I've used Python 3.7 and 3.8. I believe that I am passing everything to payment.decrypt(token['header']['ephemeralPublicKey'], token['data'])

**Comment by Sergii-Kravets** [comment]
@mike6626 @halturin 
Hi.
I have the same error.
Can you help me with that?

**Comment by Sergii-Kravets** [comment]
As I understand only EllipticCurvePrivateKey has this attribute.
But Apple only wants the RSA key.
