### ISSUE TITLE
License for private/commercial use

### ISSUE THREAD

**Issue by crintus** [halturin/applepay#9]
Hey, love your library, it's amazing.
We would love for it to be useable in both a private and commercial setting, but according to Github's licensing page, without a license we are unable to do so: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

If your repo is free for anyone to use, please add a license to it 😄

**Comment by halturin** [comment]
Hi, thanks! glad to hear that. I've just added the LICENSE file. You can use this code for free :)

**Comment by crintus** [comment]
What a champ, thank you 😊
